apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - redis.yaml

namespace: grading-pdf-prod


images:
  - name: chunchiehdev/grading-pdf
    newTag: master

replicas:
  - name: grading-pdf-api
    count: 3
  - name: grading-pdf-worker
    count: 3

patches:
  # Add pod metadata environment variables for K8s
  - target:
      kind: Deployment
      name: grading-pdf-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
      - op: add
        path: /spec/template/spec/containers/0/env/1
        value:
          name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
      - op: add
        path: /spec/template/spec/containers/0/env/2
        value:
          name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
      # Patch ConfigMap references to use -prod suffix
      - op: replace
        path: /spec/template/spec/containers/0/env/3/valueFrom/configMapKeyRef/name
        value: grading-pdf-config-prod
      - op: replace
        path: /spec/template/spec/containers/0/env/4/valueFrom/configMapKeyRef/name
        value: grading-pdf-config-prod
      - op: replace
        path: /spec/template/spec/containers/0/env/5/valueFrom/configMapKeyRef/name
        value: grading-pdf-config-prod
  - target:
      kind: Deployment
      name: grading-pdf-worker
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value:
          name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
      - op: add
        path: /spec/template/spec/containers/0/env/1
        value:
          name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
      - op: add
        path: /spec/template/spec/containers/0/env/2
        value:
          name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
      # Patch ConfigMap references to use -prod suffix
      - op: replace
        path: /spec/template/spec/containers/0/env/3/valueFrom/configMapKeyRef/name
        value: grading-pdf-config-prod
      - op: replace
        path: /spec/template/spec/containers/0/env/4/valueFrom/configMapKeyRef/name
        value: grading-pdf-config-prod
      - op: replace
        path: /spec/template/spec/containers/0/env/5/valueFrom/configMapKeyRef/name
        value: grading-pdf-config-prod

configMapGenerator:
  - name: grading-pdf-config-prod
    behavior: create
    literals:
      - REDIS_URL=redis://redis-prod:6379/0
      - APP_MODE=production
      - LOG_LEVEL=info
      - WORKER_CONCURRENCY=4

generatorOptions:
  disableNameSuffixHash: true
