apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gradsystem-ingress
  namespace: prod
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/responseforwarding.flushinterval: "1ms"
    traefik.ingress.kubernetes.io/buffering.maxrequestbodybytes: "0"
    traefik.ingress.kubernetes.io/buffering.memrequestbodybytes: "0"
    traefik.ingress.kubernetes.io/request-timeout: "600s"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
      - snapshot.agenticgrader.com
    secretName: snapshot-agenticgrader-tls
  rules:
  - host: snapshot.agenticgrader.com
    http:
      paths:
      - path: /socket.io
        pathType: Prefix
        backend:
          service:
            name: websocket-service
            port:
              number: 3001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gradsystem-service
            port:
              number: 80
