apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: websocket
        image: chunchiehdev/websocket-server:master
        env:
        - name: NODE_ENV
          value: "production"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: REDIS_PASSWORD
        - name: ALLOWED_ORIGINS
          value: "https://snapshot.agenticgrader.com,https://www.agenticgrader.com"
        - name: MAIN_API_URL
          value: "http://gradsystem"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: OPENAI_API_KEY
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GEMINI_API_KEY
