apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-api.yaml
  - deployment-worker.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: grading-pdf
  app.kubernetes.io/component: pdf-service
