apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - migration-job.yaml
  - websocket-deployment.yaml
  - websocket-service.yaml

commonLabels:
  app.kubernetes.io/name: gradsystem
  app.kubernetes.io/component: main-service
