apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  labels:
    app.kubernetes.io/name: websocket
    app.kubernetes.io/component: websocket-server
spec:
  selector:
    app.kubernetes.io/name: websocket
    app.kubernetes.io/component: websocket-server
    ws-role: websocket
  ports:
  - name: websocket
    port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
