apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gradsystem-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/responseforwarding.flushinterval: "1ms"
    traefik.ingress.kubernetes.io/buffering.maxrequestbodybytes: "0"
    traefik.ingress.kubernetes.io/buffering.memrequestbodybytes: "0"
    traefik.ingress.kubernetes.io/request-timeout: "600s"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
      # TODO: Update hostname for prod-k8s environment
      - student-mars.grading.software
    secretName: student-mars-grading-software-tls
  rules:
  - host: student-mars.grading.software
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gradsystem-service
            port:
              number: 80
