apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - redis.yaml

namespace: grading-pdf

images:
  - name: chunchiehdev/grading-pdf
    newTag: master

replicas:
  - name: grading-pdf-api
    count: 3
  - name: grading-pdf-worker
    count: 3

configMapGenerator:
  - name: grading-pdf-config
    behavior: create
    literals:
      - REDIS_URL=redis://redis:6379/0
      - APP_MODE=production
      - LOG_LEVEL=info
      - WORKER_CONCURRENCY=4

generatorOptions:
  disableNameSuffixHash: true
