apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradsystem
spec:
  template:
    spec:
      containers:
      - name: gradsystem
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: REDIS_HOST
          value: "redis-dev"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: REDIS_PASSWORD
        - name: MINIO_ENDPOINT
          value: "minio-service-dev"
        - name: MINIO_PORT
          value: "9000"
        - name: MINIO_BUCKET
          value: "grading-files"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: gradsystem-config
              key: MINIO_ROOT_USER
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: MINIO_ROOT_PASSWORD
        - name: OLLAMA_API_URL
          valueFrom:
            configMapKeyRef:
              name: gradsystem-config
              key: OLLAMA_API_URL
        - name: OLLAMA_API_KEY
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: OLLAMA_API_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: DATABASE_URL
        - name: THEME_SECRET
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: THEME_SECRET
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: AUTH_SECRET
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GOOGLE_CLIENT_SECRET
        - name: GOOGLE_REDIRECT_URI
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GOOGLE_REDIRECT_URI
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GEMINI_API_KEY
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: AUTH_KEY
        - name: PDF_PARSER_API_URL
          valueFrom:
            configMapKeyRef:
              name: gradsystem-config
              key: PDF_PARSER_API_URL
        - name: GEMINI_API_KEY2
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GEMINI_API_KEY2
        - name: GEMINI_API_KEY3
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GEMINI_API_KEY3
        - name: PRISMA_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: gradsystem-config
              key: PRISMA_LOG_LEVEL
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: OPENAI_API_KEY
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: POSTGRES_PASSWORD
        - name: GOOGLE_SEARCH_API_KEY
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GOOGLE_SEARCH_API_KEY
        - name: GOOGLE_SEARCH_ENGINE_ID
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GOOGLE_SEARCH_ENGINE_ID
